baseURL: "http://silverxb.xyz/"
title: silverxb's blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: silverxb's blog
  description: "Technical Sharing & Life Sharing"
  keywords: [Blog, Portfolio, PaperMod]
  author: silverxb
  # author: ["Me", "You"] # multiple authors
  images: ["http://silverxb.xyz/img/profile_photo.jpg"]
  DateFormat: "March 2, 2023"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Silverxb's Blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Silverxb's Blog
    subtitle: Master Student, Zhejiang University
    description: Technical Sharing & Life Sharing.
    imageUrl: "http://silverxb.xyz/img/profile_photo.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile
    buttons:
      - name: Technical
        url: tech
      - name: Life
        url: life
      - name: Others
        url: others

  # home-info mode
  homeInfoParams:
    Title: "Hi there"
    Content: Welcome to my blog

  socialIcons:
  #  - name: twitter
  #    url: "https://twitter.com/"
  #  - name: stackoverflow
  #    url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/silverzdz"
    - name: bilibili
      url: "https://space.bilibili.com/2683532"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/silverzdz/mypage/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tech
      name: Technical
      url: /tech/
      weight: 20
    - identifier: Contact me
      name: Contact me
      url: mailto:1023814324@qq.com
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai